description: 'Linux executor containing integration scripts for the Hal Deployment Portal'

parameters:
    repository:
        description: 'Docker registry/repository to use.'
        type: string
        default: 'qldockerdtr.rockfin.com/circleci/hal-integration'
    tag:
        description: 'Docker tag to use.'
        type: string
        default: 'hal-publisher'

docker:
    - image: '<<parameters.repository>>:<<parameters.tag>>'
